import Constants from 'expo-constants';
import { router } from 'expo-router';
import { useState } from 'react';
import {
  ActivityIndicator,
  KeyboardAvoidingView,
  Platform,
  Pressable,
  SafeAreaView,
  StyleSheet,
  Text,
  TextInput,
  View,
} from 'react-native';

import { palette, radius } from '@/lib/theme';
import { useOwnerSession } from '@/state/session';

export default function SetupScreen() {
  const { pair } = useOwnerSession();
  const defaultUrl =
    (process.env.EXPO_PUBLIC_OWNER_GATEWAY_URL?.trim() ||
      (Constants.expoConfig?.extra?.ownerGatewayDefaultUrl as string | undefined) ||
      'https://owner.quickfurno.in');
  const [gatewayUrl, setGatewayUrl] = useState(defaultUrl);
  const [pairingCode, setPairingCode] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function submit() {
    if (pairingCode.trim().length < 6) {
      setError('Enter the pairing code generated by AGNI Owner Gateway.');
      return;
    }
    setBusy(true);
    setError(null);
    try {
      await pair({ gatewayUrl, pairingCode });
      router.replace('/(tabs)');
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : 'Pairing failed.');
    } finally {
      setBusy(false);
    }
  }

  return (
    <SafeAreaView style={styles.safe}>
      <KeyboardAvoidingView
        style={styles.flex}
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
      >
        <View style={styles.content}>
          <View style={styles.mark}>
            <Text style={styles.markText}>A</Text>
          </View>
          <Text style={styles.eyebrow}>QUICKFURNO OWNER INTELLIGENCE</Text>
          <Text style={styles.title}>Pair this device with AGNI.</Text>
          <Text style={styles.body}>
            The app stores only a device session in Android secure storage. OpenAI and production
            credentials remain server-side behind AGNI.
          </Text>

          <View style={styles.form}>
            <Text style={styles.label}>Owner Gateway</Text>
            <TextInput
              value={gatewayUrl}
              onChangeText={setGatewayUrl}
              autoCapitalize="none"
              autoCorrect={false}
              keyboardType="url"
              style={styles.input}
              placeholder="https://owner.quickfurno.in"
              placeholderTextColor={palette.muted}
            />

            <Text style={styles.label}>Pairing code</Text>
            <TextInput
              value={pairingCode}
              onChangeText={setPairingCode}
              autoCapitalize="characters"
              autoCorrect={false}
              style={styles.input}
              placeholder="AGNI-XXXXXX"
              placeholderTextColor={palette.muted}
            />

            {error ? <Text style={styles.error}>{error}</Text> : null}

            <Pressable
              accessibilityRole="button"
              disabled={busy}
              onPress={() => void submit()}
              style={({ pressed }) => [styles.button, pressed && styles.buttonPressed]}
            >
              {busy ? (
                <ActivityIndicator color={palette.bg} />
              ) : (
                <Text style={styles.buttonText}>Pair securely</Text>
              )}
            </Pressable>
          </View>
        </View>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.bg },
  flex: { flex: 1 },
  content: { flex: 1, justifyContent: 'center', padding: 24, gap: 14 },
  mark: {
    width: 54,
    height: 54,
    borderRadius: 18,
    backgroundColor: palette.accent,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  markText: { color: palette.bg, fontSize: 28, fontWeight: '900' },
  eyebrow: { color: palette.accent, fontSize: 11, letterSpacing: 1.5, fontWeight: '800' },
  title: { color: palette.text, fontSize: 32, lineHeight: 37, fontWeight: '900' },
  body: { color: palette.muted, fontSize: 15, lineHeight: 22, maxWidth: 520 },
  form: {
    marginTop: 18,
    padding: 18,
    borderRadius: radius.lg,
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.border,
    gap: 10,
  },
  label: { color: palette.text, fontSize: 12, fontWeight: '800', marginTop: 4 },
  input: {
    color: palette.text,
    backgroundColor: palette.surface2,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: radius.md,
    paddingHorizontal: 14,
    paddingVertical: 13,
    fontSize: 14,
  },
  error: { color: palette.red, fontSize: 12, lineHeight: 17 },
  button: {
    backgroundColor: palette.accent,
    borderRadius: radius.md,
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
  },
  buttonPressed: { opacity: 0.85 },
  buttonText: { color: palette.bg, fontSize: 15, fontWeight: '900' },
});
